# Generated by Django 5.2.17 on 2026-10-02 12:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "kg"),
                            ("pcs", "pieces"),
                            ("L", "litre"),
                            ("pkt", "packet"),
                        ],
                        default="pcs",
                        max_length=5,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Latest purchase price per unit (₹). Used to value losses.",
                        max_digits=10,
                    ),
                ),
                (
                    "low_stock_level",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Warn when stock falls to this level (0 = no warning).",
                        max_digits=10,
                    ),
                ),
                (
                    "is_key",
                    models.BooleanField(
                        default=False,
                        help_text="Show on the dashboard (e.g. chicken, roti).",
                    ),
                ),
                (
                    "count_daily",
                    models.BooleanField(
                        default=True, help_text="Ask for a physical count at day close."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(db_index=True)),
                (
                    "counted_qty",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "expected_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "variance_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counts",
                        to="stock.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "stock_item__sort_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business_date", "stock_item"),
                        name="uniq_count_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Owner has confirmed this quantity."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "addon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="menu.addon",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="menu.variant",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_lines",
                        to="stock.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["stock_item__sort_order", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("addon__isnull", True), ("variant__isnull", False)
                            ),
                            models.Q(
                                ("addon__isnull", False), ("variant__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="recipe_line_variant_xor_addon",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("variant__isnull", False)),
                        fields=("stock_item", "variant"),
                        name="uniq_recipe_variant",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("addon__isnull", False)),
                        fields=("stock_item", "addon"),
                        name="uniq_recipe_addon",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("sale", "Used in sales"),
                            ("wastage", "Wastage / spoiled"),
                            ("staff_meal", "Staff meal"),
                            ("adjust", "Correction"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("delta", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("business_date", models.DateField(db_index=True)),
                ("note", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="orders.order",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="stock.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stock_item", "business_date", "kind"],
                        name="stock_stock_stock_i_a9f829_idx",
                    )
                ],
            },
        ),
    ]
