# Generated by Django 5.2.17 on 2026-10-02 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(default="Lavish Shawarma", max_length=80),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, default="Fresh • Juicy • Loaded", max_length=120
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="Mancherial, Telangana", max_length=200
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "receipt_footer",
                    models.CharField(
                        blank=True, default="Thank you! Visit again.", max_length=200
                    ),
                ),
                ("bill_prefix", models.CharField(default="LS", max_length=8)),
                (
                    "receipt_width_mm",
                    models.PositiveSmallIntegerField(
                        choices=[(58, "58 mm"), (80, "80 mm")], default=80
                    ),
                ),
                (
                    "day_starts_at_hour",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Orders before this hour (0-23) belong to the previous business day.",
                    ),
                ),
                (
                    "max_open_orders_per_staff",
                    models.PositiveSmallIntegerField(
                        default=15,
                        help_text="Unpaid, not-cancelled orders a staff member may have at once.",
                    ),
                ),
                (
                    "max_orders_per_minute",
                    models.PositiveSmallIntegerField(
                        default=6,
                        help_text="Orders a staff member may create per minute.",
                    ),
                ),
                (
                    "staff_max_discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Discounts above this % need admin approval.",
                    ),
                ),
                (
                    "staff_can_record",
                    models.BooleanField(
                        default=False,
                        help_text="Let staff record stock purchases, wastage, expenses and the day close (they still cannot edit or delete).",
                    ),
                ),
                (
                    "staff_can_mark_sold_out",
                    models.BooleanField(
                        default=True, help_text="Let staff mark items as sold out."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "shop settings",
                "verbose_name_plural": "shop settings",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=60)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False, help_text="Blocked devices cannot use the app."
                    ),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("action", models.CharField(db_index=True, max_length=40)),
                ("model", models.CharField(db_index=True, max_length=60)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
