# Generated by Django 5.2.17 on 2026-10-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="table_count",
            field=models.PositiveSmallIntegerField(
                default=8,
                help_text="How many dine-in tables to show as quick buttons on the billing screen (0 = none).",
            ),
        ),
    ]
