# Generated by Django 5.2.17 on 2026-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="upi_id",
            field=models.CharField(
                blank=True,
                help_text="Your UPI ID for the payment QR, e.g. lavishshawarma@okaxis. Leave empty to hide the QR.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="upi_name",
            field=models.CharField(
                blank=True,
                default="Lavish Shawarma",
                help_text="Name shown in the customer's UPI app.",
                max_length=60,
            ),
        ),
    ]
