# Generated by Django 5.2.17 on 2026-10-02 12:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DayClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(unique=True)),
                (
                    "opening_cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "cash_sales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "cash_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "expected_cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "counted_cash",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "cash_difference",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "cash_removed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Cash taken out of the drawer (to owner / bank). The rest stays as tomorrow's opening cash.",
                        max_digits=10,
                    ),
                ),
                (
                    "upi_sales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "card_sales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "online_sales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "unpaid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("orders_count", models.PositiveIntegerField(default=0)),
                ("cancelled_count", models.PositiveIntegerField(default=0)),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "stock_loss_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("closed_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_date", models.DateField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stock", "Stock purchase (chicken, roti…)"),
                            ("grocery", "Vegetables & groceries"),
                            ("gas", "Gas / fuel"),
                            ("packaging", "Packaging"),
                            ("salary", "Salary / wages"),
                            ("rent", "Rent"),
                            ("electricity", "Electricity & water"),
                            ("maintenance", "Repairs & maintenance"),
                            ("transport", "Transport"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(max_length=150)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "paid_from",
                    models.CharField(
                        choices=[
                            ("drawer", "Cash drawer (counter)"),
                            ("upi", "UPI / bank"),
                            ("owner", "Owner's pocket"),
                        ],
                        default="drawer",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense",
                        to="stock.stockmovement",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-created_at"],
            },
        ),
    ]
