# Generated by Django 5.2.17 on 2026-10-02 12:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Addon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("veg", "Veg"),
                            ("non_veg", "Non-veg"),
                            ("egg", "Egg"),
                        ],
                        default="veg",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Shorter name for buttons and receipts (optional).",
                        max_length=30,
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("veg", "Veg"),
                            ("non_veg", "Non-veg"),
                            ("egg", "Egg"),
                        ],
                        default="non_veg",
                        max_length=10,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide from the menu completely.",
                    ),
                ),
                (
                    "is_sold_out",
                    models.BooleanField(
                        default=False,
                        help_text="Temporarily sold out (still on the menu).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "addons",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Extras allowed on this item.",
                        related_name="items",
                        to="menu.addon",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "ordering": ["category__sort_order", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Regular", max_length=30)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="menu.item",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "sort_order", "price"],
            },
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="uniq_item_name_per_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="variant",
            constraint=models.UniqueConstraint(
                fields=("item", "name"), name="uniq_variant_name_per_item"
            ),
        ),
    ]
