# Generated by Django 5.2.17 on 2026-10-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="table_no",
            field=models.CharField(
                blank=True, help_text="Table number for dine-in orders.", max_length=10
            ),
        ),
    ]
