# Generated by Django 5.2.17 on 2026-10-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("dine_in", "Dine-in"),
                    ("takeaway", "Takeaway"),
                    ("online", "Online"),
                    ("parcel", "Parcel (old)"),
                ],
                default="dine_in",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("zomato", "Zomato"),
                    ("swiggy", "Swiggy"),
                    ("foodatdoor", "FoodAtDoor"),
                    ("other", "Other"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
